import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "../../providers/providers";
import CharacterNavbar from "@/src/components/navbar/character-list.navbar";
import MenuNavbar from "@/src/components/navbar/menu.navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="bg-[url(/bg.png)] bg-fixed bg-cover bg-center">
        <Providers>
          <MenuNavbar />
          <CharacterNavbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
